apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  # claimRef:
  #   namespace: demo
  #   name: pvc-nfs
  nfs:
    server: 10.9.44.11
    path: /nfs
