apiVersion: v1
kind: Service
metadata:
  name: test-server
  labels:
    app: test-server
spec:
  type: ClusterIP
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: test-server
