apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pv
  template:
    metadata:
      name: test-pv
      labels:
        app: test-pv
    spec:
      containers:
      - image: docker.io/dennischou/test-server:v1.1.2
        imagePullPolicy: Always
        name: test-pv
        volumeMounts:
        - mountPath: /workspace/files
          name: data-pvc
      volumes:
      - name: data-pvc
        persistentVolumeClaim:
          claimName: pvc-nfs
