apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-test-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-test-env
  template:
    metadata:
      labels:
        app: config-test-env
    spec:
      containers:
      - name: config-test-env
        image: docker.io/dennischou/test-server:v1.1.2
        env:
        - name: VERSION    
          valueFrom:
            configMapKeyRef:
              name: config-test
              key: version.data
