apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test-dir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-test-dir
  template:
    metadata:
      labels:
        app: secret-test-dir
    spec:
      containers:
      - name: secret-test-dir
        image: docker.io/dennischou/test-server
        volumeMounts:
        - name: secret-volume
          mountPath: /tmp/data
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-test
