apiVersion: v1
kind: Service
metadata:
  name: config-test-env
  labels:
    app: config-test-env
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: config-test-env